[versions]
javalin = "7.2.3"
jte = "3.2.4"
slf4j = "2.0.18"
h2 = "2.4.240"
postgresql = "42.7.13"
hikaricp = "7.1.0"
unirest = "3.14.5"
jsoup = "1.21.2"
junit = "5.13.4"
assertj = "3.27.7"
mockwebserver = "4.12.0"
versions-plugin = "0.52.0"
spotless-plugin = "7.2.1"

[libraries]
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
javalin-rendering-jte = { module = "io.javalin:javalin-rendering-jte", version.ref = "javalin" }
jte = { module = "gg.jte:jte", version.ref = "jte" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
unirest = { module = "com.konghq:unirest-java", version.ref = "unirest" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
