DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id      BIGINT NOT NULL REFERENCES urls (id) ON DELETE CASCADE,
    status_code INTEGER NOT NULL,
    h1          TEXT,
    title       TEXT,
    description TEXT,
    created_at  TIMESTAMP NOT NULL
);
